---
title: "Final Paper"
author: "Sasa Tang"
date: "5/1/2018"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This paper will use geospatial sexual harassment incident data from [Safecity](http://safecity.in), a 
nonprofit with an online platform that maps out sexual harassment using crowd 
sourced pin locations in India to examine the relationship between different types 
of sexual harassment in public spaces. This paper looks into the relationship 
between five main categories of sexual harassment: non-direct, direct verbal, 
physical, stalking, and others. \par

This repository contains the following information:\par 


1. [Safecity.Rproj] (https://github.com/SasaTang/SafeCityIndia/blob/master/Safecity.Rproj)\par

    This is an R Project file that contains the R Markdown for the paper and all the below code.\par
    
    
2.	[MapClean.R] (https://github.com/SasaTang/SafeCityIndia/blob/master/mapClean.R)\par

    This is the R code for the creation of the maps in the final paper.
    
3.	[Datacleanup.R] (https://github.com/SasaTang/SafeCityIndia/blob/master/datacleanup.R)\par

    This is the code to clean up the data, transforming the original csv into useable data for this paper. For the original csv, please contact [Safecity](http://safecity.in/contact-us/). \par
    
    
4.	[BasicStat.R](https://github.com/SasaTang/SafeCityIndia/blob/master/BasicStat.R)\par

    This is the code that is used to examine the data, to see descriptive
    
    
5.	[Tang_Presentation.tex](https://github.com/SasaTang/SafeCityIndia/blob/master/Tang_Presentation.tex)\par

    This the LaTex document of the final presentation.
    
    
6.	[Tang_Presentation.pdf](https://github.com/SasaTang/SafeCityIndia/blob/master/Tang_Presentation.pdf)\par

    This is the PDF of the final presentation.
    
  
7.	[FinalPaper.pdf](https://github.com/SasaTang/SafeCityIndia/blob/master/FinalPaper.pdf)\par

    This is the final paper of this project. 

8.  [delhi_highway.shp](https://github.com/SasaTang/SafeCityIndia/blob/master/delhi_highway.shp)\par

    This is the shapefile for the roads for New Delhi


10. [IND_admn2.shp](https://github.com/SasaTang/SafeCityIndia/blob/master/IND_adm2.shp)\par

    This is the shapefile for the districts in India

